import type { Metadata } from "next";
import { Inter, Fraunces } from "next/font/google";
import "./globals.css";

const inter= Inter({
  variable: "--font-inter",
  subsets: ["latin"]
});

const fraunces= Fraunces({
 variable: "--font-fraunces",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} ${fraunces.variable}   antialiased`} >
        <div className="mobile-shell  " >
          <div className="overflow-y-auto flex-1 no-scrollbar">
              {children}
          </div>
        </div>
      </body>
    </html>
  );
}
